# Generated by Django 3.2.12 on 2022-06-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_intallemnt', models.PositiveIntegerField()),
                ('monthly_intallemnt', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('interest_rate', models.PositiveIntegerField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ad')),
            ],
        ),
        migrations.DeleteModel(
            name='Imageffff',
        ),
    ]
