# Generated by Django 3.2.12 on 2022-06-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20220617_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='cash_discount',
            field=models.DecimalField(decimal_places=2, default=2.2, max_digits=4),
            preserve_default=False,
        ),
    ]
