# Generated by Django 3.2.12 on 2022-06-18 21:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_cash_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=''), default=[], size=30),
            preserve_default=False,
        ),
    ]
