# Generated by Django 3.2.12 on 2022-06-19 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_ad_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.ad'),
        ),
    ]
