# Generated by Django 3.2.12 on 2022-06-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_image_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
